### ISSUE TITLE
using array instead of eloquent models

### ISSUE THREAD

**Issue by mostafa-rz** [robsontenorio/mary#3]
Is it possible to use arrays instead of eloquent models in the select or choices tag?
I tried out and I was unsuccessful.

**Comment by robsontenorio** [comment]
@mostafa-rz Jus released "0.32.0".  Now it allows array syntax. Please, upgrade and let me know if everything is ok.

**Comment by mostafa-rz** [comment]
I got this error for each option in the select.
```
app-5db76317.js:1 Alpine Expression Error: Cannot read properties of null (reading 'includes')

Expression: "
                                                                            selection.includes(37) && 'bg-primary/5'
                                                                    "

 <div wire:key=​"option-37" @click=​"
                                    $refs.inputSearch.value = '';​
                                    toggle(JSON.parse('{\u0022id\u0022:​37,\u0022name\u0022:​\u0022wm-em-wetten.de\u0022}​')​)​;​
                                    
                                    
                                                                    " :class=​"
                                                                            selection.includes(37)​ && 'bg-primary/​5'
                                                                    " class>​<!-- ITEM SLOT --><div wire:key=​"6c3d797f-a106-482e-bc5e-6b0ba9bbb9a5">​…​</div>​</div>​
Y @ app-5db76317.js:1
129app-5db76317.js:5 Uncaught TypeError: Cannot read properties of null (reading 'includes')
    at eval (eval at <anonymous> (app-5db76317.js:5:638), <anonymous>:4:87)
    at app-5db76317.js:5:976
    at Qn (app-5db76317.js:1:5629)
    at app-5db76317.js:5:30539
    at n (app-5db76317.js:5:15955)
    at Object.Jr [as effect] (app-5db76317.js:5:15743)
    at z (app-5db76317.js:1:1132)
    at app-5db76317.js:1:1245
    at Function.<anonymous> (app-5db76317.js:5:30533)
    at n (app-5db76317.js:5:2173)
```

**Comment by robsontenorio** [comment]
@mostafa-rz 

1 - how looks like `$app` ?
2 - just self close `<x-list-item … />`

**Comment by mostafa-rz** [comment]
![image](https://github.com/robsontenorio/mary/assets/71334549/e4c3d86b-0c45-4b06-ac50-07526b912004)

**Comment by mostafa-rz** [comment]
Yes, I tried that out,
Thanks!

**Comment by davidcabcab** [comment]
I can't get the x-choice showing "tags" using a simple array. 

Livewire component class :  
 ```
public $tags_choice = [];

public function mount()
    {
           $this->tags_choice = [
           ['id' => '1', 'name' => 'tech'],
           ['id' => '2', 'name' => 'asd']
        ];
    }
```

Blade view : 
```
<div>
    <x-choices label="choice test" wire:model="tags_choice" />
</div>
```
Result : 
<img width="556" alt="Capture d’écran 2024-02-24 à 21 50 52" src="https://github.com/robsontenorio/mary/assets/153238958/9fcddad0-1eae-4290-8e71-e566b091c83b">

Console error : 

> 
> Alpine Expression Error: Cannot read properties of undefined (reading 'name')
> 
> Expression: "option.name"

> Uncaught TypeError: Cannot read properties of undefined (reading 'name')
>     at [Alpine] option.name (eval at safeAsyncFunction (livewire.js?id=6b5eb707:1249:21), <anonymous>:3:39)
>     at livewire.js?id=6b5eb707:1271:23
>     at tryCatch (livewire.js?id=6b5eb707:1191:14)
>     at livewire.js?id=6b5eb707:3406:7
>     at reactiveEffect (livewire.js?id=6b5eb707:2365:18)
>     at Object.effect2 [as effect] (livewire.js?id=6b5eb707:2340:7)
>     at effect (livewire.js?id=6b5eb707:726:35)
>     at wrappedEffect (livewire.js?id=6b5eb707:742:29)
>     at Function.<anonymous> (livewire.js?id=6b5eb707:3405:5)
>     at flushHandlers (livewire.js?id=6b5eb707:1353:48)
> 
>  
>

**Comment by robsontenorio** [comment]
@davidcabcab 

The `<x-choices />` does not works like this way. Take a look on very first examples.

- The `wire:model` holds the selected key.
- It needs a `:option` list to display.

**Comment by davidcabcab** [comment]
Ok, I got it.

This works : 

 ```
    public $selectedTags = [];

    public $options = [];

    public function mount()
    {
        $this->selectedTags =[1,2];

        $this->options = [
            ['id' => '1', 'name' => 'first'],
            ['id' => '2', 'name' => 'sec'],
            ['id' => '3', 'name' => 'third']
        ];
    }
```
`    <x-choices label="Multiple" wire:model="selectedTags" :options="$options" />
`

Maybe an example like in your demo  would be very useful for any newbie like me 😅

**Comment by robsontenorio** [comment]
As I said before  it is on very first docs about Choices. Of course, the variable names can be anything.

<img width="837" alt="image" src="https://github.com/robsontenorio/mary/assets/118955/e382206b-dfca-4f92-ad15-99b49f888442">
